# Generated by Django 3.0.6 on 2020-05-06 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='About the work')),
                ('responsibility', models.TextField(verbose_name="Selected intern's day-to-day responsibilities include")),
                ('skills', models.CharField(max_length=100)),
                ('perks', models.CharField(max_length=100)),
                ('who_can_apply', models.TextField(verbose_name="Selected intern's day-to-day responsibilities include")),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('available', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=2)),
                ('category', models.CharField(choices=[('Android App Development', 'Android App Development'), ('  Angular.js Development', '  Angular.js Development'), ('Software Developer', 'Software Developer'), ('Consultant', 'Consultant'), ('Accountant', 'Accountant'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Electrician', 'Electrician'), ('Graphic Designer', 'Graphic Designer'), ('Writer and Editor', 'Writer and Editor'), ('Market Research Analyst', 'Market Research Analyst'), ('Interpreter and Translator', 'Interpreter and Translator'), ('Architect', 'Architect'), ('Chemist', 'Chemist'), ('Database Administrator', 'Database Administrator'), ('Customer Service Representative', 'Customer Service Representative'), ('Fashion Designer', 'Fashion Designer')], max_length=100)),
                ('daerah', models.CharField(choices=[('Works from Home', 'Works from Home'), ('Tawau', 'Tawau'), ('Sandakan', 'Sandakan'), ('Lahad Datu', 'Lahad Datu'), ('Kota Kinabalu', 'Kota Kinabalu'), ('Semporna', 'Semporna')], max_length=100)),
                ('duration', models.CharField(choices=[('1 Months', '1 Months'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
