# Generated by Django 3.0.6 on 2020-05-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='who_can_apply',
        ),
        migrations.AddField(
            model_name='post',
            name='who_apply',
            field=models.TextField(default='Human', verbose_name='Who can apply'),
            preserve_default=False,
        ),
    ]
