# Generated by Django 3.0.6 on 2020-05-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0002_auto_20200506_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
